/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_number = 2,
  anon_sym_DOT = 3,
  anon_sym_LBRACE = 4,
  anon_sym_COLON = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_let = 9,
  anon_sym_COLON_EQ = 10,
  anon_sym_in = 11,
  anon_sym_forall = 12,
  anon_sym_COMMA = 13,
  anon_sym_fun = 14,
  anon_sym_EQ_GT = 15,
  anon_sym_match = 16,
  anon_sym_with = 17,
  anon_sym_PIPE = 18,
  anon_sym_end = 19,
  anon_sym_if = 20,
  anon_sym_then = 21,
  anon_sym_else = 22,
  anon_sym_Definition = 23,
  anon_sym_Example = 24,
  anon_sym_Theorem = 25,
  anon_sym_Lemma = 26,
  anon_sym_Fact = 27,
  anon_sym_Remark = 28,
  anon_sym_Corollary = 29,
  anon_sym_Hypothesis = 30,
  anon_sym_Variable = 31,
  anon_sym_Variables = 32,
  sym_module = 33,
  sym__command = 34,
  sym_type = 35,
  sym_implicit_binder = 36,
  sym_explicit_binder = 37,
  sym_open_binder = 38,
  sym_binder = 39,
  sym_pattern = 40,
  sym_term = 41,
  sym_term_expr = 42,
  sym_term_let = 43,
  sym_term_forall = 44,
  sym_term_fun = 45,
  sym_term_match = 46,
  sym_term_if = 47,
  sym_declaration = 48,
  sym_definition_kind = 49,
  sym_theorem_kind = 50,
  sym_assumption_kind = 51,
  aux_sym_module_repeat1 = 52,
  aux_sym_implicit_binder_repeat1 = 53,
  aux_sym_term_let_repeat1 = 54,
  aux_sym_term_match_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_let] = "let",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_in] = "in",
  [anon_sym_forall] = "forall",
  [anon_sym_COMMA] = ",",
  [anon_sym_fun] = "fun",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_match] = "match",
  [anon_sym_with] = "with",
  [anon_sym_PIPE] = "|",
  [anon_sym_end] = "end",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_Definition] = "Definition",
  [anon_sym_Example] = "Example",
  [anon_sym_Theorem] = "Theorem",
  [anon_sym_Lemma] = "Lemma",
  [anon_sym_Fact] = "Fact",
  [anon_sym_Remark] = "Remark",
  [anon_sym_Corollary] = "Corollary",
  [anon_sym_Hypothesis] = "Hypothesis",
  [anon_sym_Variable] = "Variable",
  [anon_sym_Variables] = "Variables",
  [sym_module] = "module",
  [sym__command] = "_command",
  [sym_type] = "type",
  [sym_implicit_binder] = "implicit_binder",
  [sym_explicit_binder] = "explicit_binder",
  [sym_open_binder] = "open_binder",
  [sym_binder] = "binder",
  [sym_pattern] = "pattern",
  [sym_term] = "term",
  [sym_term_expr] = "term_expr",
  [sym_term_let] = "term_let",
  [sym_term_forall] = "term_forall",
  [sym_term_fun] = "term_fun",
  [sym_term_match] = "term_match",
  [sym_term_if] = "term_if",
  [sym_declaration] = "declaration",
  [sym_definition_kind] = "definition_kind",
  [sym_theorem_kind] = "theorem_kind",
  [sym_assumption_kind] = "assumption_kind",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_implicit_binder_repeat1] = "implicit_binder_repeat1",
  [aux_sym_term_let_repeat1] = "term_let_repeat1",
  [aux_sym_term_match_repeat1] = "term_match_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_forall] = anon_sym_forall,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_Definition] = anon_sym_Definition,
  [anon_sym_Example] = anon_sym_Example,
  [anon_sym_Theorem] = anon_sym_Theorem,
  [anon_sym_Lemma] = anon_sym_Lemma,
  [anon_sym_Fact] = anon_sym_Fact,
  [anon_sym_Remark] = anon_sym_Remark,
  [anon_sym_Corollary] = anon_sym_Corollary,
  [anon_sym_Hypothesis] = anon_sym_Hypothesis,
  [anon_sym_Variable] = anon_sym_Variable,
  [anon_sym_Variables] = anon_sym_Variables,
  [sym_module] = sym_module,
  [sym__command] = sym__command,
  [sym_type] = sym_type,
  [sym_implicit_binder] = sym_implicit_binder,
  [sym_explicit_binder] = sym_explicit_binder,
  [sym_open_binder] = sym_open_binder,
  [sym_binder] = sym_binder,
  [sym_pattern] = sym_pattern,
  [sym_term] = sym_term,
  [sym_term_expr] = sym_term_expr,
  [sym_term_let] = sym_term_let,
  [sym_term_forall] = sym_term_forall,
  [sym_term_fun] = sym_term_fun,
  [sym_term_match] = sym_term_match,
  [sym_term_if] = sym_term_if,
  [sym_declaration] = sym_declaration,
  [sym_definition_kind] = sym_definition_kind,
  [sym_theorem_kind] = sym_theorem_kind,
  [sym_assumption_kind] = sym_assumption_kind,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_implicit_binder_repeat1] = aux_sym_implicit_binder_repeat1,
  [aux_sym_term_let_repeat1] = aux_sym_term_let_repeat1,
  [aux_sym_term_match_repeat1] = aux_sym_term_match_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_forall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Definition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Example] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Theorem] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Lemma] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Fact] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Remark] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Corollary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Hypothesis] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Variable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Variables] = {
    .visible = true,
    .named = false,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym__command] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_binder] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_binder] = {
    .visible = true,
    .named = true,
  },
  [sym_open_binder] = {
    .visible = true,
    .named = true,
  },
  [sym_binder] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_term_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_term_let] = {
    .visible = true,
    .named = true,
  },
  [sym_term_forall] = {
    .visible = true,
    .named = true,
  },
  [sym_term_fun] = {
    .visible = true,
    .named = true,
  },
  [sym_term_match] = {
    .visible = true,
    .named = true,
  },
  [sym_term_if] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_definition_kind] = {
    .visible = true,
    .named = true,
  },
  [sym_theorem_kind] = {
    .visible = true,
    .named = true,
  },
  [sym_assumption_kind] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_implicit_binder_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_let_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_match_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_binder = 1,
  field_body = 2,
  field_match_case = 3,
  field_name = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_binder] = "binder",
  [field_body] = "body",
  [field_match_case] = "match_case",
  [field_name] = "name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 2},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 1},
  [12] = {.index = 21, .length = 4},
  [13] = {.index = 25, .length = 5},
  [14] = {.index = 30, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_body, 2},
    {field_name, 1},
  [3] =
    {field_body, 3},
    {field_name, 1},
  [5] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [7] =
    {field_binder, 2},
    {field_body, 3},
    {field_name, 1},
  [10] =
    {field_name, 1, .inherited = true},
  [11] =
    {field_name, 0, .inherited = true},
    {field_type, 2},
  [13] =
    {field_binder, 2},
    {field_body, 4},
    {field_name, 1},
  [16] =
    {field_binder, 1},
    {field_body, 3},
  [18] =
    {field_name, 1, .inherited = true},
    {field_type, 3},
  [20] =
    {field_match_case, 3},
  [21] =
    {field_body, 3},
    {field_body, 4},
    {field_body, 5},
    {field_name, 1},
  [25] =
    {field_binder, 2},
    {field_body, 4},
    {field_body, 5},
    {field_body, 6},
    {field_name, 1},
  [30] =
    {field_body, 5},
    {field_body, 6},
    {field_body, 7},
    {field_name, 1},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        '(', 9,
        ')', 10,
        ',', 12,
        '.', 5,
        ':', 7,
        '=', 1,
        '{', 6,
        '|', 14,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '>') ADVANCE(13);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(11);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'C', 1,
        'D', 2,
        'E', 3,
        'F', 4,
        'H', 5,
        'L', 6,
        'R', 7,
        'T', 8,
        'V', 9,
        'e', 10,
        'f', 11,
        'i', 12,
        'l', 13,
        'm', 14,
        't', 15,
        'w', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'x') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'y') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(28);
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(39);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(55);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(58);
      END_STATE();
    case 42:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 47:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 50:
      if (lookahead == 'c') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == 'h') ADVANCE(66);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 55:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_Fact);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 58:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 61:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 64:
      if (lookahead == 'h') ADVANCE(76);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 67:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 68:
      if (lookahead == 'i') ADVANCE(78);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 70:
      if (lookahead == 'h') ADVANCE(80);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_Lemma);
      END_STATE();
    case 72:
      if (lookahead == 'k') ADVANCE(81);
      END_STATE();
    case 73:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 74:
      if (lookahead == 'b') ADVANCE(83);
      END_STATE();
    case 75:
      if (lookahead == 'l') ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 80:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_Remark);
      END_STATE();
    case 82:
      if (lookahead == 'm') ADVANCE(89);
      END_STATE();
    case 83:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_forall);
      END_STATE();
    case 85:
      if (lookahead == 'r') ADVANCE(91);
      END_STATE();
    case 86:
      if (lookahead == 'i') ADVANCE(92);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_Example);
      END_STATE();
    case 88:
      if (lookahead == 's') ADVANCE(93);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_Theorem);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 91:
      if (lookahead == 'y') ADVANCE(95);
      END_STATE();
    case 92:
      if (lookahead == 'o') ADVANCE(96);
      END_STATE();
    case 93:
      if (lookahead == 'i') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_Variable);
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_Corollary);
      END_STATE();
    case 96:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 97:
      if (lookahead == 's') ADVANCE(100);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_Variables);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_Definition);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_Hypothesis);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_forall] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_Definition] = ACTIONS(1),
    [anon_sym_Example] = ACTIONS(1),
    [anon_sym_Theorem] = ACTIONS(1),
    [anon_sym_Lemma] = ACTIONS(1),
    [anon_sym_Fact] = ACTIONS(1),
    [anon_sym_Remark] = ACTIONS(1),
    [anon_sym_Corollary] = ACTIONS(1),
    [anon_sym_Hypothesis] = ACTIONS(1),
    [anon_sym_Variable] = ACTIONS(1),
    [anon_sym_Variables] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_module] = STATE(69),
    [sym__command] = STATE(15),
    [sym_declaration] = STATE(83),
    [sym_definition_kind] = STATE(86),
    [sym_theorem_kind] = STATE(86),
    [sym_assumption_kind] = STATE(86),
    [aux_sym_module_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_Definition] = ACTIONS(5),
    [anon_sym_Example] = ACTIONS(5),
    [anon_sym_Theorem] = ACTIONS(7),
    [anon_sym_Lemma] = ACTIONS(7),
    [anon_sym_Fact] = ACTIONS(7),
    [anon_sym_Remark] = ACTIONS(7),
    [anon_sym_Corollary] = ACTIONS(7),
    [anon_sym_Hypothesis] = ACTIONS(9),
    [anon_sym_Variable] = ACTIONS(11),
    [anon_sym_Variables] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_term,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(64), 1,
      sym_type,
    STATE(3), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [54] = 15,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    STATE(7), 1,
      sym_term,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(66), 1,
      sym_type,
    STATE(14), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [108] = 2,
    ACTIONS(33), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(31), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [134] = 2,
    ACTIONS(37), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(35), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [160] = 2,
    ACTIONS(41), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(39), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [186] = 2,
    ACTIONS(45), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(43), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [212] = 2,
    ACTIONS(49), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(47), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [238] = 2,
    ACTIONS(53), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(51), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [264] = 2,
    ACTIONS(57), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(55), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [290] = 2,
    ACTIONS(61), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(59), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [316] = 2,
    ACTIONS(65), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(63), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [342] = 2,
    ACTIONS(69), 10,
      sym_number,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_PIPE,
    ACTIONS(67), 11,
      sym_identifier,
      anon_sym_let,
      anon_sym_in,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_with,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
  [368] = 8,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(14), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
    ACTIONS(74), 4,
      sym_number,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
    ACTIONS(82), 5,
      anon_sym_let,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_if,
  [403] = 8,
    ACTIONS(11), 1,
      anon_sym_Variable,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    STATE(83), 1,
      sym_declaration,
    ACTIONS(5), 2,
      anon_sym_Definition,
      anon_sym_Example,
    ACTIONS(9), 2,
      anon_sym_Hypothesis,
      anon_sym_Variables,
    STATE(16), 2,
      sym__command,
      aux_sym_module_repeat1,
    STATE(86), 3,
      sym_definition_kind,
      sym_theorem_kind,
      sym_assumption_kind,
    ACTIONS(7), 5,
      anon_sym_Theorem,
      anon_sym_Lemma,
      anon_sym_Fact,
      anon_sym_Remark,
      anon_sym_Corollary,
  [437] = 8,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      anon_sym_Variable,
    STATE(83), 1,
      sym_declaration,
    ACTIONS(88), 2,
      anon_sym_Definition,
      anon_sym_Example,
    ACTIONS(94), 2,
      anon_sym_Hypothesis,
      anon_sym_Variables,
    STATE(16), 2,
      sym__command,
      aux_sym_module_repeat1,
    STATE(86), 3,
      sym_definition_kind,
      sym_theorem_kind,
      sym_assumption_kind,
    ACTIONS(91), 5,
      anon_sym_Theorem,
      anon_sym_Lemma,
      anon_sym_Fact,
      anon_sym_Remark,
      anon_sym_Corollary,
  [471] = 10,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(7), 1,
      sym_term,
    STATE(80), 1,
      sym_type,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [507] = 10,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(7), 1,
      sym_term,
    STATE(76), 1,
      sym_type,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [543] = 10,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(7), 1,
      sym_term,
    STATE(79), 1,
      sym_type,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [579] = 10,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(7), 1,
      sym_term,
    STATE(10), 1,
      sym_type,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [615] = 10,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(7), 1,
      sym_term,
    STATE(38), 1,
      sym_type,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [651] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(67), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [684] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(70), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [717] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(81), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [750] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(65), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [783] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(11), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [816] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(72), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [849] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(5), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [882] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(4), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [915] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(78), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [948] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(9), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [981] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(77), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [1014] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(13), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [1047] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(63), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [1080] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(68), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [1113] = 9,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_forall,
    ACTIONS(25), 1,
      anon_sym_fun,
    ACTIONS(27), 1,
      anon_sym_match,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(84), 1,
      sym_term,
    STATE(8), 6,
      sym_term_expr,
      sym_term_let,
      sym_term_forall,
      sym_term_fun,
      sym_term_match,
      sym_term_if,
  [1146] = 2,
    ACTIONS(102), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_if,
    ACTIONS(104), 6,
      sym_number,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
  [1163] = 2,
    ACTIONS(106), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_if,
    ACTIONS(108), 6,
      sym_number,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
  [1180] = 2,
    ACTIONS(110), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_if,
    ACTIONS(112), 6,
      sym_number,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
  [1197] = 2,
    ACTIONS(114), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_if,
    ACTIONS(116), 6,
      sym_number,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
  [1214] = 2,
    ACTIONS(118), 6,
      sym_identifier,
      anon_sym_let,
      anon_sym_forall,
      anon_sym_fun,
      anon_sym_match,
      anon_sym_if,
    ACTIONS(120), 6,
      sym_number,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_COLON_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
  [1231] = 8,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(124), 1,
      anon_sym_COLON,
    ACTIONS(126), 1,
      anon_sym_COLON_EQ,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(47), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1259] = 2,
    ACTIONS(130), 1,
      anon_sym_Variable,
    ACTIONS(128), 10,
      ts_builtin_sym_end,
      anon_sym_Definition,
      anon_sym_Example,
      anon_sym_Theorem,
      anon_sym_Lemma,
      anon_sym_Fact,
      anon_sym_Remark,
      anon_sym_Corollary,
      anon_sym_Hypothesis,
      anon_sym_Variables,
  [1275] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(132), 1,
      anon_sym_EQ_GT,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(14), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1300] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_COLON_EQ,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(46), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1325] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_COLON_EQ,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(14), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1350] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_COLON_EQ,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(14), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1375] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(14), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1400] = 6,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(44), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1422] = 6,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(53), 1,
      aux_sym_implicit_binder_repeat1,
    STATE(48), 2,
      sym_binder,
      aux_sym_term_let_repeat1,
    STATE(39), 3,
      sym_implicit_binder,
      sym_explicit_binder,
      sym_open_binder,
  [1444] = 4,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(142), 1,
      anon_sym_COLON,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_implicit_binder_repeat1,
  [1457] = 3,
    ACTIONS(146), 1,
      sym_identifier,
    STATE(52), 1,
      aux_sym_implicit_binder_repeat1,
    ACTIONS(149), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
  [1468] = 3,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(151), 1,
      anon_sym_COLON,
    STATE(52), 1,
      aux_sym_implicit_binder_repeat1,
  [1478] = 2,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(153), 2,
      sym_identifier,
      anon_sym_COLON,
  [1486] = 2,
    STATE(74), 1,
      sym_pattern,
    ACTIONS(155), 2,
      sym_identifier,
      sym_number,
  [1494] = 3,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(157), 1,
      anon_sym_COLON,
    STATE(52), 1,
      aux_sym_implicit_binder_repeat1,
  [1504] = 3,
    ACTIONS(159), 1,
      anon_sym_PIPE,
    ACTIONS(161), 1,
      anon_sym_end,
    STATE(58), 1,
      aux_sym_term_match_repeat1,
  [1514] = 3,
    ACTIONS(163), 1,
      anon_sym_PIPE,
    ACTIONS(166), 1,
      anon_sym_end,
    STATE(58), 1,
      aux_sym_term_match_repeat1,
  [1524] = 1,
    ACTIONS(153), 3,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_RBRACE,
  [1530] = 2,
    ACTIONS(159), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_term_match_repeat1,
  [1537] = 2,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(51), 1,
      aux_sym_implicit_binder_repeat1,
  [1544] = 2,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(56), 1,
      aux_sym_implicit_binder_repeat1,
  [1551] = 1,
    ACTIONS(168), 2,
      anon_sym_PIPE,
      anon_sym_end,
  [1556] = 1,
    ACTIONS(170), 1,
      anon_sym_DOT,
  [1560] = 1,
    ACTIONS(172), 1,
      anon_sym_then,
  [1564] = 1,
    ACTIONS(174), 1,
      anon_sym_DOT,
  [1568] = 1,
    ACTIONS(176), 1,
      anon_sym_else,
  [1572] = 1,
    ACTIONS(178), 1,
      anon_sym_DOT,
  [1576] = 1,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
  [1580] = 1,
    ACTIONS(182), 1,
      anon_sym_DOT,
  [1584] = 1,
    ACTIONS(184), 1,
      sym_identifier,
  [1588] = 1,
    ACTIONS(186), 1,
      anon_sym_in,
  [1592] = 1,
    ACTIONS(188), 1,
      anon_sym_EQ_GT,
  [1596] = 1,
    ACTIONS(190), 1,
      anon_sym_EQ_GT,
  [1600] = 1,
    ACTIONS(192), 1,
      sym_identifier,
  [1604] = 1,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
  [1608] = 1,
    ACTIONS(196), 1,
      anon_sym_DOT,
  [1612] = 1,
    ACTIONS(198), 1,
      anon_sym_in,
  [1616] = 1,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
  [1620] = 1,
    ACTIONS(202), 1,
      anon_sym_COLON_EQ,
  [1624] = 1,
    ACTIONS(204), 1,
      anon_sym_in,
  [1628] = 1,
    ACTIONS(206), 1,
      sym_identifier,
  [1632] = 1,
    ACTIONS(208), 1,
      anon_sym_DOT,
  [1636] = 1,
    ACTIONS(210), 1,
      anon_sym_with,
  [1640] = 1,
    ACTIONS(212), 1,
      sym_identifier,
  [1644] = 1,
    ACTIONS(214), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 134,
  [SMALL_STATE(6)] = 160,
  [SMALL_STATE(7)] = 186,
  [SMALL_STATE(8)] = 212,
  [SMALL_STATE(9)] = 238,
  [SMALL_STATE(10)] = 264,
  [SMALL_STATE(11)] = 290,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 342,
  [SMALL_STATE(14)] = 368,
  [SMALL_STATE(15)] = 403,
  [SMALL_STATE(16)] = 437,
  [SMALL_STATE(17)] = 471,
  [SMALL_STATE(18)] = 507,
  [SMALL_STATE(19)] = 543,
  [SMALL_STATE(20)] = 579,
  [SMALL_STATE(21)] = 615,
  [SMALL_STATE(22)] = 651,
  [SMALL_STATE(23)] = 684,
  [SMALL_STATE(24)] = 717,
  [SMALL_STATE(25)] = 750,
  [SMALL_STATE(26)] = 783,
  [SMALL_STATE(27)] = 816,
  [SMALL_STATE(28)] = 849,
  [SMALL_STATE(29)] = 882,
  [SMALL_STATE(30)] = 915,
  [SMALL_STATE(31)] = 948,
  [SMALL_STATE(32)] = 981,
  [SMALL_STATE(33)] = 1014,
  [SMALL_STATE(34)] = 1047,
  [SMALL_STATE(35)] = 1080,
  [SMALL_STATE(36)] = 1113,
  [SMALL_STATE(37)] = 1146,
  [SMALL_STATE(38)] = 1163,
  [SMALL_STATE(39)] = 1180,
  [SMALL_STATE(40)] = 1197,
  [SMALL_STATE(41)] = 1214,
  [SMALL_STATE(42)] = 1231,
  [SMALL_STATE(43)] = 1259,
  [SMALL_STATE(44)] = 1275,
  [SMALL_STATE(45)] = 1300,
  [SMALL_STATE(46)] = 1325,
  [SMALL_STATE(47)] = 1350,
  [SMALL_STATE(48)] = 1375,
  [SMALL_STATE(49)] = 1400,
  [SMALL_STATE(50)] = 1422,
  [SMALL_STATE(51)] = 1444,
  [SMALL_STATE(52)] = 1457,
  [SMALL_STATE(53)] = 1468,
  [SMALL_STATE(54)] = 1478,
  [SMALL_STATE(55)] = 1486,
  [SMALL_STATE(56)] = 1494,
  [SMALL_STATE(57)] = 1504,
  [SMALL_STATE(58)] = 1514,
  [SMALL_STATE(59)] = 1524,
  [SMALL_STATE(60)] = 1530,
  [SMALL_STATE(61)] = 1537,
  [SMALL_STATE(62)] = 1544,
  [SMALL_STATE(63)] = 1551,
  [SMALL_STATE(64)] = 1556,
  [SMALL_STATE(65)] = 1560,
  [SMALL_STATE(66)] = 1564,
  [SMALL_STATE(67)] = 1568,
  [SMALL_STATE(68)] = 1572,
  [SMALL_STATE(69)] = 1576,
  [SMALL_STATE(70)] = 1580,
  [SMALL_STATE(71)] = 1584,
  [SMALL_STATE(72)] = 1588,
  [SMALL_STATE(73)] = 1592,
  [SMALL_STATE(74)] = 1596,
  [SMALL_STATE(75)] = 1600,
  [SMALL_STATE(76)] = 1604,
  [SMALL_STATE(77)] = 1608,
  [SMALL_STATE(78)] = 1612,
  [SMALL_STATE(79)] = 1616,
  [SMALL_STATE(80)] = 1620,
  [SMALL_STATE(81)] = 1624,
  [SMALL_STATE(82)] = 1628,
  [SMALL_STATE(83)] = 1632,
  [SMALL_STATE(84)] = 1636,
  [SMALL_STATE(85)] = 1640,
  [SMALL_STATE(86)] = 1644,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_let, 6, 0, 12),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_let, 6, 0, 12),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_let, 8, 0, 14),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_let, 8, 0, 14),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_expr, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_expr, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_if, 6, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_if, 6, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_forall, 4, 0, 9),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_forall, 4, 0, 9),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_fun, 4, 0, 9),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_fun, 4, 0, 9),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_match, 5, 0, 11),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_match, 5, 0, 11),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_let, 7, 0, 13),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_let, 7, 0, 13),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_let_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_let_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_let_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_let_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_let_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_implicit_binder, 3, 0, 6),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implicit_binder, 3, 0, 6),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_open_binder, 3, 0, 7),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_binder, 3, 0, 7),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binder, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binder, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_explicit_binder, 5, 0, 10),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_binder, 5, 0, 10),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_implicit_binder, 5, 0, 10),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implicit_binder, 5, 0, 10),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_implicit_binder_repeat1, 2, 0, 4), SHIFT_REPEAT(59),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_implicit_binder_repeat1, 2, 0, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_implicit_binder_repeat1, 1, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_match_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_match_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_match_repeat1, 4, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_kind, 3, 0, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theorem_kind, 4, 0, 5),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_kind, 5, 0, 8),
  [180] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assumption_kind, 3, 0, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_kind, 4, 0, 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tree_sitter_rocq(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tree_sitter_rocq",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
